language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  include:
    - php: 7.3
      env:
        - COMPAT_VERSION=7.3
        - RUN_TESTS="composer/semver:^1.0"
    - php: 7.3
      env:
        - COMPAT_VERSION=7.3
        - RUN_TESTS="composer/semver:^2.0"
    - php: 7.3
      env:
        - COMPAT_VERSION=7.3
        - RUN_TESTS="composer/semver:^3.0"
    - php: 7.4
      env:
        - COMPAT_VERSION=7.4
    - php: 8.0
      env:
        - COMPAT_VERSION=8.0
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

before_install:
  - composer self-update --1

install:
  - composer update $COMPOSER_ARGS
  - if [[ $RUN_TESTS != '' ]]; then composer require $RUN_TESTS ; fi
  - stty cols 120 && composer show

script:
  - if [[ $RUN_TESTS != '' ]]; then composer test ; fi
  - composer cs-check -- -p src --standard=PHPCompatibility --runtime-set testVersion $COMPAT_VERSION

notifications:
  email: false
